name: Continuous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          npm i -g pnpm
          SHELL=bash pnpm setup
          source /home/runner/.bashrc

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm install -D vsce
          pnpm dlx vsce package --no-yarn

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest
          path: vscord-*.vsix
