name: Continuous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Build
        run: |
          npm i -g vsce
          vsce package --no-yarn

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: vscord-*.vsix
